@startuml
participant User as u
participant "Wallet Frontend" as w
participant "Wallet Backend" as b
participant Issuer as i

u -> w : get credential
w -> b : start credential issuance : authz url
w --> i : authorize
i --> w : authorize response (code)
w -> b : exchange code (code, app attestation) : tx_token, c_nonce
b -> b : check app_attestation
b -> i : token (code, client_id, ...): access_token, c_nonce
note right: wallet authenticates with issuer\nissuer may check wallet against trust registry
w -> w : gen key : key, key_attestation
w -> w : create proof of posssion
w -> b : request credential (tx_token, type, format, proof, key_attestation): credential
b -> b : check key_attestation
b -> i : issue credential (type, format, proof): credential
@enduml