@startuml

actor User as U
participant Wallet as W
box Issuer
participant "Issuer Site" as IS
participant "Server Metadata" as metadata
participant "Nonce Endpoint" as init
participant "Pushed Authorization Endpoint" as PAR
participant "Authorization Endpoint" as AS
participant "Token Endpoint" as T
participant "Credential Endpoint" as P
participant "Deferred Credential" as I
end box
autoactivate on
hide footbox

IS -> W: Initiate Issuance (issuer, op_state, ...)

U -> W: interact

W->P: credentials (user_pin, type, did, proof)
note over W: better called issuance endpoint?

return credential or acceptance_token(, c_nonce)

note over W: better called credential collection endpoint?
W->I: deferred credential request (acceptance_token)
return credential

@enduml